version: '3.8'

services:
  api:
    build: ./server      
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - FRONT_ORIGIN_URL=${FRONT_ORIGIN_URL}
    volumes:
      - ./server:/server
    command: npm run debug

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  client:
    build: ./app
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    volumes: 
      - ./app:/app
    links:
      - api
    command: npm run start
  
volumes:
  mongodb: