version: '3.8'

services:
  api:
    build: ./server      
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
    volumes:
      - ./server:/server
    command: npm run debug

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  
volumes:
  mongodb: